"""update_type_branchcode

Revision ID: 01af78e169d2
Revises: ef9ad9d16128
Create Date: 2023-10-17 17:35:27.568919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01af78e169d2'
down_revision: Union[str, None] = 'ef9ad9d16128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_account', ['nomor_rekening'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_account', type_='unique')
    # ### end Alembic commands ###
