"""initial

Revision ID: 063e7957240f
Revises: 
Create Date: 2023-10-09 16:09:48.613056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063e7957240f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_branch',
    sa.Column('id_branch', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_branch')
    )
    op.create_table('tb_user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('hp', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('tb_account',
    sa.Column('id_account', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_branch'], ['tb_branch.id_branch'], ),
    sa.ForeignKeyConstraint(['id_user'], ['tb_user.id_user'], ),
    sa.PrimaryKeyConstraint('id_account')
    )
    op.create_table('tb_transaction',
    sa.Column('id_transaction', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('type_transaction', sa.Enum('DEBIT', 'CREDIT', 'TRANSFER', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['tb_account.id_account'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['tb_account.id_account'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_transaction')
    op.drop_table('tb_account')
    op.drop_table('tb_user')
    op.drop_table('tb_branch')
    # ### end Alembic commands ###
