"""updateUSER_column_isAdmin

Revision ID: a5068817932c
Revises: 16f72a8488ce
Create Date: 2023-10-11 15:14:58.301543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5068817932c'
down_revision: Union[str, None] = '16f72a8488ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'isAdmin')
    # ### end Alembic commands ###
