"""update_column_first

Revision ID: ef9ad9d16128
Revises: 
Create Date: 2023-10-17 16:47:35.487249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9ad9d16128'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_branch',
    sa.Column('id_branch', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('branch_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_branch'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('tb_user',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('hp', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_account',
    sa.Column('id_account', sa.UUID(), nullable=False),
    sa.Column('nomor_rekening', sa.String(length=10), nullable=True),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('id_branch', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_branch'], ['tb_branch.id_branch'], ),
    sa.ForeignKeyConstraint(['id_user'], ['tb_user.id_user'], ),
    sa.PrimaryKeyConstraint('nomor_rekening'),
    sa.UniqueConstraint('nomor_rekening')
    )
    op.create_table('tb_transaction',
    sa.Column('id_transaction', sa.UUID(), nullable=False),
    sa.Column('nomor_rekening', sa.String(length=10), nullable=True),
    sa.Column('type_transaction', sa.Enum('DEBIT', 'CREDIT', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nomor_rekening'], ['tb_account.nomor_rekening'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_transaction')
    op.drop_table('tb_account')
    op.drop_table('tb_user')
    op.drop_table('tb_branch')
    # ### end Alembic commands ###
